name: Production Deployment with Manual Approval

on:
  workflow_dispatch: # Allows manual triggering
  push: # Triggers on push to any branches
    branches: [ '*' ]
  pull_request: # Triggers on pull requests
    branches: [ '*' ]

jobs:
  # --- MANUAL APPROVAL GATE ---
  wait-for-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.APPROVAL_TOKEN }}  # Optional security
          approvers: "rafi13us"  # GitHub usernames who can approve

  # --- PRODUCTION DEPLOYMENT (AFTER APPROVAL) ---
  deploy-prod:
    needs: wait-for-approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Production Archive
        run: |
          mkdir -p archive
          tar -czf archive/repo.tar.gz --exclude='.git' .

      - name: Upload to Production
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "archive/repo.tar.gz"
          target: "/tmp/repo.tar.gz"

      - name: Deploy to Production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            DEPLOY_DIR="/var/www/production"
            sudo mkdir -p $DEPLOY_DIR
            sudo tar -xzf /tmp/repo.tar.gz -C $DEPLOY_DIR --overwrite
            rm /tmp/repo.tar.gz
            sudo systemctl restart nginx  # Example service restart


