name: Sync Repository to Target Folder

on:
  workflow_dispatch: # Allows manual triggering
  push: # Triggers on push to any branches
    branches: [ '*' ]
  pull_request: # Triggers on pull requests
    branches: [ '*' ]

jobs:
  sync-repo:
    runs-on: self-hosted # Uses your self-hosted runner
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetches all history and tags
        
    - name: Create repository archive
      run: |
        powershell Compress-Archive -Path * -DestinationPath repo_archive.zip -Force
        
    - name: Create target directory if it doesn't exist
      run: |
        $targetFolder = "C:\DeploymentTarget" # Change this to your desired target folder
        if (-not (Test-Path -Path $targetFolder)) {
          New-Item -ItemType Directory -Path $targetFolder -Force
          Write-Output "Created target directory: $targetFolder"
        }
        
    - name: Copy and extract archive to target folder
      run: |
        $targetFolder = "C:\DeploymentTarget" # Must match the folder above
        $archivePath = "$env:GITHUB_WORKSPACE\repo_archive.zip"
        
        # Copy the zip file
        Copy-Item -Path $archivePath -Destination $targetFolder -Force
        
        # Extract the zip file
        powershell Expand-Archive -Path "$targetFolder\repo_archive.zip" -DestinationPath $targetFolder -Force
        
        # Clean up the zip file in target folder (optional)
        Remove-Item -Path "$targetFolder\repo_archive.zip" -Force
        
        Write-Output "Repository contents updated in: $targetFolder"
        
    - name: Verify contents in target folder
      run: |
        $targetFolder = "C:\DeploymentTarget" # Must match the folder above
        Get-ChildItem -Path $targetFolder -Recurse | Select-Object FullName | Out-String -Width 200
    
    - name: Send success email
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Success: Repository Synced to Target Folder"
        body: |
          The DataMetrics repository has been successfully synchronized to the target folder.
          
          Details:
          - Target Location: ${{ env.TARGET_FOLDER }}
          - Files Deployed: ${{ env.FILE_COUNT }}
          - Triggered by: ${{ github.event_name }}
          - Repository: ${{ github.repository }}
          - Commit: ${{ github.sha }}
          
          Date: ${{ steps.date.outputs.date }}
        to: mohammedrafi.shaik@gmail.com  # Replace with your email
        from: GitHub Actions